const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export class ModelService {
  async *streamResponse(userMessage: string): AsyncGenerator<string> {
    const text = [
      `# Mock Markdown + LaTeX stress response`,
      ``,
      `Ban vua gui: **${userMessage}**`,
      ``,
      `> Muc tieu cua doan mock nay la tao nhieu dang Markdown, KaTeX, bang, list va code block de kiem tra renderer.`,
      ``,
      `## 1. Checklist Markdown`,
      ``,
      `- **Bold text** va *italic text* trong cung mot cau.`,
      `- Inline code: \`const score = alpha * beta;\`.`,
      `- Inline math bang dollar: $E = mc^2$ va $\\nabla \\cdot \\vec{E} = \\frac{\\rho}{\\varepsilon_0}$.`,
      `- Inline math bang marker: \\( a^2 + b^2 = c^2 \\).`,
      `- Link mau: [GitHub](https://github.com).`,
      ``,
      `## 2. Bang so lieu`,
      ``,
      `| Metric | Value | Formula | Note |`,
      `| --- | ---: | --- | --- |`,
      `| perplexity | 12.42 | $e^{H(p,q)}$ | lower is better |`,
      `| accuracy | 98.1% | $\\frac{TP+TN}{N}$ | synthetic |`,
      `| latency | 34ms | $p95 < 50ms$ | renderer budget |`,
      `| tokens | 4096 | $O(n^2)$ attention | stress case |`,
      ``,
      `## 3. Display math bang $$`,
      ``,
      `$$`,
      `\\mathcal{L}(\\theta) = -\\sum_{t=1}^{T} \\log p_\\theta(y_t \\mid y_{<t}, x) + \\lambda \\lVert \\theta \\rVert_2^2`,
      `$$`,
      ``,
      `Mot he phuong trinh co canh hang:`,
      ``,
      `\\[`,
      `\\begin{aligned}`,
      `x_{t+1} &= A x_t + B u_t \\\\`,
      `y_t &= C x_t + \\epsilon_t \\\\`,
      `J &= \\sum_{t=0}^{T} \\left(x_t^T Q x_t + u_t^T R u_t\\right)`,
      `\\end{aligned}`,
      `\\]`,
      ``,
      `Ma tran block:`,
      ``,
      `$$`,
      `K = \\begin{bmatrix}`,
      `K_{xx} & K_{xz} \\\\`,
      `K_{zx} & K_{zz}`,
      `\\end{bmatrix}, \\qquad`,
      `K^{-1} = \\frac{1}{\\det(K)} \\operatorname{adj}(K)`,
      `$$`,
      ``,
      `## 4. Code block TypeScript`,
      ``,
      "```ts",
      `type RenderSample = {`,
      `  id: string;`,
      `  markdown: boolean;`,
      `  latex: "inline" | "display";`,
      `  metrics: Record<string, number>;`,
      `};`,
      ``,
      `export function summarize(sample: RenderSample): string {`,
      `  const total = Object.values(sample.metrics).reduce((sum, value) => sum + value, 0);`,
      `  return \`\${sample.id}: \${total.toFixed(2)}\`;`,
      `}`,
      "```",
      ``,
      `## 5. Code block Python`,
      ``,
      "```python",
      `import math`,
      ``,
      `def softmax(xs):`,
      `    scale = max(xs)`,
      `    exps = [math.exp(x - scale) for x in xs]`,
      `    total = sum(exps)`,
      `    return [x / total for x in exps]`,
      ``,
      `print(softmax([1.0, 2.0, 3.0]))`,
      "```",
      ``,
      `## 6. JSON config`,
      ``,
      "```json",
      `{`,
      `  "renderer": "react-markdown",`,
      `  "math": ["$", "\\\\(", "\\\\[", "$$"],`,
      `  "codeBlock": {`,
      `    "engine": "shiki+monaco",`,
      `    "copyButton": true`,
      `  }`,
      `}`,
      "```",
      ``,
      `## 7. Nested list`,
      ``,
      `1. Parser`,
      `   - tach fenced code truoc`,
      `   - sau do xu ly math display`,
      `2. Renderer`,
      `   - code block dung Shiki khi complete`,
      `   - Monaco readonly khi streaming`,
      `3. Scroll`,
      `   - chi auto khi dang o day`,
      `   - user scroll len thi dung auto`,
      ``,
      `Ket luan: neu UI on dinh, bang, math display, inline math va nhieu code block se render khong bi vo layout.`,
    ].join("\n");

    for (const char of Array.from(text)) {
      await delay(2);
      yield char;
    }
  }
}
